apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
spec:
  containers:
  - name: mariadb
    image: mariadb:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: mariadb-root-password
    ports:
      - containerPort: 3306
    volumeMounts:
      - name: mariadb-data
        mountPath: /var/lib/mysql
  volumes:
    - name: mariadb-data
      hostPath:
        path: ~/cloudcomputing/db
        type: DirectoryOrCreate
